"""
============================================================
INTELLILINK X1
============================================================

AI-POWERED PREDICTIVE MULTI-CONNECTIVITY
NETWORK MANAGEMENT SYSTEM

Developer:
    MSAFIRI GROUP

Application:
    IntelliLink X1

Backend:
    FastAPI

Database:
    SQLite

Version:
    0.1.0

============================================================
IMPORTANT
============================================================

This is a software prototype.

Device identifiers generated by database.py are internal
IntelliLink identifiers. They are NOT:

    - IMEI
    - IMSI
    - ICCID
    - Real SIM identity
    - Carrier identity

Real hardware identifiers must come from actual hardware
when IntelliLink X1 is eventually deployed on dedicated
hardware.

The application does NOT store Wi-Fi passwords.
============================================================
"""

from __future__ import annotations

import os
import platform
import socket
import statistics
import subprocess
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles


# ============================================================
# DATABASE
# ============================================================

try:
    from database import (
        DATABASE_PATH,
        create_device,
        database_health,
        get_dashboard_summary,
        get_device,
        get_device_settings,
        get_diagnostics,
        get_events,
        get_network_history,
        get_speed_history,
        initialize_intellilink,
        log_event,
        record_network_switch,
        save_diagnostic,
        save_network_sample,
        save_speed_test,
        update_device,
    )

    DATABASE_AVAILABLE = True

except Exception as database_import_error:

    DATABASE_AVAILABLE = False

    DATABASE_PATH = None

    DATABASE_IMPORT_ERROR = str(database_import_error)


# ============================================================
# APPLICATION CONFIGURATION
# ============================================================

APP_NAME = "IntelliLink X1"

APP_VERSION = "0.1.0"

API_VERSION = "v1"

PRODUCT_FAMILY = "IntelliLink X-Series"

MANUFACTURER = "IntelliLink Systems"

DEVELOPER = "MSAFIRI GROUP"

DEVICE_TYPE = "Network Management System"

DEFAULT_COUNTRY = "TZ"

DEFAULT_TIMEZONE = "Africa/Dar_es_Salaam"


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

STATIC_DIR = BASE_DIR / "static"

INDEX_FILE = BASE_DIR / "index.html"


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title=APP_NAME,
    description=(
        "AI-powered predictive multi-connectivity "
        "network management system."
    ),
    version=APP_VERSION,
    docs_url="/docs",
    redoc_url="/redoc",
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,

    allow_origins=["*"],

    allow_credentials=True,

    allow_methods=["*"],

    allow_headers=["*"],
)


# ============================================================
# STATIC FILES
# ============================================================

if STATIC_DIR.exists():

    app.mount(
        "/static",
        StaticFiles(directory=str(STATIC_DIR)),
        name="static",
    )


# ============================================================
# GLOBAL RUNTIME STATE
# ============================================================

START_TIME = time.time()

LAST_NETWORK_SNAPSHOT: Optional[dict[str, Any]] = None

LAST_SPEED_TEST: Optional[dict[str, Any]] = None

LAST_DIAGNOSTICS: Optional[dict[str, Any]] = None


# ============================================================
# TIME UTILITIES
# ============================================================

def utc_now() -> str:
    """
    Return current UTC time as ISO-8601 string.
    """

    return datetime.now(
        timezone.utc
    ).isoformat()


# ============================================================
# SAFE VALUE HELPERS
# ============================================================

def safe_str(
    value: Any,
    fallback: str = "N/A",
) -> str:

    if value is None:
        return fallback

    text = str(value).strip()

    if not text:
        return fallback

    return text


def safe_float(
    value: Any,
) -> Optional[float]:

    try:

        if value is None:
            return None

        number = float(value)

        if number != number:
            return None

        return number

    except (
        TypeError,
        ValueError,
    ):

        return None


# ============================================================
# SYSTEM INFORMATION
# ============================================================

def get_platform_info() -> dict[str, Any]:

    return {
        "system": platform.system(),
        "release": platform.release(),
        "version": platform.version(),
        "machine": platform.machine(),
        "architecture": platform.architecture()[0],
        "processor": platform.processor(),
        "python_version": platform.python_version(),
        "hostname": socket.gethostname(),
    }


# ============================================================
# HOSTNAME
# ============================================================

def get_hostname() -> str:

    try:

        return socket.gethostname()

    except Exception:

        return "N/A"


# ============================================================
# LOCAL IP
# ============================================================

def get_local_ip() -> Optional[str]:

    sock = None

    try:

        sock = socket.socket(
            socket.AF_INET,
            socket.SOCK_DGRAM,
        )

        sock.settimeout(1)

        sock.connect(
            (
                "8.8.8.8",
                80,
            )
        )

        return sock.getsockname()[0]

    except Exception:

        return None

    finally:

        if sock:

            try:
                sock.close()
            except Exception:
                pass


# ============================================================
# DEFAULT GATEWAY
# ============================================================

def get_default_gateway() -> Optional[str]:

    system = platform.system().lower()

    try:

        if system == "windows":

            result = subprocess.run(
                [
                    "route",
                    "print",
                    "0.0.0.0",
                ],
                capture_output=True,
                text=True,
                timeout=3,
            )

            for line in result.stdout.splitlines():

                parts = line.split()

                if (
                    len(parts) >= 3
                    and parts[0] == "0.0.0.0"
                ):

                    return parts[2]

        else:

            result = subprocess.run(
                [
                    "ip",
                    "route",
                ],
                capture_output=True,
                text=True,
                timeout=3,
            )

            for line in result.stdout.splitlines():

                parts = line.split()

                if (
                    len(parts) >= 3
                    and parts[0] == "default"
                    and parts[1] == "via"
                ):

                    return parts[2]

    except Exception:

        pass

    return None


# ============================================================
# NETWORK INTERFACE
# ============================================================

def get_network_interface() -> Optional[str]:

    system = platform.system().lower()

    try:

        if system == "windows":

            result = subprocess.run(
                [
                    "ipconfig",
                ],
                capture_output=True,
                text=True,
                timeout=3,
            )

            if result.returncode == 0:
                return "Windows Network Interface"

        else:

            result = subprocess.run(
                [
                    "ip",
                    "route",
                    "get",
                    "8.8.8.8",
                ],
                capture_output=True,
                text=True,
                timeout=3,
            )

            output = result.stdout.strip()

            parts = output.split()

            if "dev" in parts:

                index = parts.index("dev")

                if index + 1 < len(parts):

                    return parts[index + 1]

    except Exception:

        pass

    return None


# ============================================================
# CONNECTION TYPE
# ============================================================

def detect_connection_type() -> str:

    interface = get_network_interface()

    if not interface:

        return "UNKNOWN"

    name = interface.lower()

    if (
        "wlan" in name
        or "wifi" in name
        or name.startswith("wl")
    ):

        return "Wi-Fi"

    if (
        "eth" in name
        or "en" in name
        or "ethernet" in name
    ):

        return "Ethernet"

    if (
        "wwan" in name
        or "cell" in name
        or "rmnet" in name
    ):

        return "Cellular"

    return "NETWORK"


# ============================================================
# WIFI INFORMATION
# ============================================================

def get_wifi_info() -> dict[str, Any]:

    system = platform.system().lower()

    result: dict[str, Any] = {
        "available": False,
        "connected": False,
        "ssid": None,
        "signal": None,
        "status": "Unavailable",
        "interface": None,
        "note": None,
    }

    interface = get_network_interface()

    result["interface"] = interface

    connection_type = detect_connection_type()

    if connection_type == "Wi-Fi":

        result["available"] = True
        result["connected"] = True
        result["status"] = "Connected"

    else:

        result["status"] = "Not detected"

    # --------------------------------------------------------
    # Windows Wi-Fi
    # --------------------------------------------------------

    if system == "windows":

        try:

            output = subprocess.run(
                [
                    "netsh",
                    "wlan",
                    "show",
                    "interfaces",
                ],
                capture_output=True,
                text=True,
                timeout=4,
            ).stdout

            for line in output.splitlines():

                clean = line.strip()

                if clean.startswith("SSID"):

                    if ":" in clean:

                        result["ssid"] = (
                            clean.split(":", 1)[1]
                            .strip()
                        )

                elif clean.startswith("Signal"):

                    if ":" in clean:

                        signal_text = (
                            clean.split(":", 1)[1]
                            .strip()
                        )

                        result["signal"] = signal_text

                elif clean.startswith("State"):

                    if ":" in clean:

                        state = (
                            clean.split(":", 1)[1]
                            .strip()
                            .lower()
                        )

                        result["connected"] = (
                            state == "connected"
                        )

        except Exception:

            pass

    # --------------------------------------------------------
    # Linux Wi-Fi
    # --------------------------------------------------------

    elif system == "linux":

        try:

            output = subprocess.run(
                [
                    "iwgetid",
                    "-r",
                ],
                capture_output=True,
                text=True,
                timeout=3,
            ).stdout.strip()

            if output:

                result["ssid"] = output
                result["available"] = True
                result["connected"] = True
                result["status"] = "Connected"

        except Exception:

            pass

    # --------------------------------------------------------
    # Android / Termux / Pydroid
    # --------------------------------------------------------

    if (
        not result["ssid"]
        and "android" in platform.platform().lower()
    ):

        result["note"] = (
            "Android may restrict Wi-Fi information "
            "without native system permissions."
        )

    return result


# ============================================================
# INTERNET CONNECTIVITY
# ============================================================

def check_internet(
    host: str = "1.1.1.1",
    port: int = 443,
    timeout: float = 3.0,
) -> bool:

    try:

        sock = socket.create_connection(
            (
                host,
                port,
            ),
            timeout=timeout,
        )

        sock.close()

        return True

    except Exception:

        return False


# ============================================================
# TCP LATENCY
# ============================================================

def measure_latency(
    host: str = "1.1.1.1",
    port: int = 443,
    attempts: int = 3,
) -> Optional[float]:

    measurements: list[float] = []

    for _ in range(attempts):

        started = time.perf_counter()

        try:

            sock = socket.create_connection(
                (
                    host,
                    port,
                ),
                timeout=3,
            )

            sock.close()

            elapsed = (
                time.perf_counter()
                - started
            ) * 1000

            measurements.append(
                elapsed
            )

        except Exception:

            continue

    if not measurements:
        return None

    return statistics.mean(
        measurements
    )


# ============================================================
# JITTER
# ============================================================

def measure_jitter(
    host: str = "1.1.1.1",
    port: int = 443,
    attempts: int = 5,
) -> Optional[float]:

    measurements: list[float] = []

    for _ in range(attempts):

        latency = measure_latency(
            host,
            port,
            attempts=1,
        )

        if latency is not None:

            measurements.append(
                latency
            )

        time.sleep(0.05)

    if len(measurements) < 2:

        return None

    differences = [
        abs(
            measurements[i]
            - measurements[i - 1]
        )
        for i in range(
            1,
            len(measurements),
        )
    ]

    return statistics.mean(
        differences
    )


# ============================================================
# NETWORK SCORE
# ============================================================

def calculate_network_score(
    latency: Optional[float],
    jitter: Optional[float],
    packet_loss: Optional[float],
    internet: bool,
) -> dict[str, Any]:

    if not internet:

        return {
            "score": 0,
            "quality": "CRITICAL",
            "description": (
                "Internet connectivity is unavailable."
            ),
        }

    score = 100.0

    # Latency
    if latency is None:

        score -= 25

    elif latency <= 40:

        score -= 0

    elif latency <= 80:

        score -= 10

    elif latency <= 150:

        score -= 20

    elif latency <= 300:

        score -= 35

    else:

        score -= 50

    # Jitter
    if jitter is not None:

        if jitter <= 10:
            score -= 0

        elif jitter <= 30:
            score -= 5

        elif jitter <= 60:
            score -= 10

        else:
            score -= 20

    # Packet loss
    if packet_loss is not None:

        if packet_loss <= 1:
            score -= 0

        elif packet_loss <= 5:
            score -= 10

        elif packet_loss <= 10:
            score -= 20

        else:
            score -= 35

    score = max(
        0,
        min(
            100,
            round(score),
        ),
    )

    if score >= 90:

        quality = "EXCELLENT"

    elif score >= 75:

        quality = "GOOD"

    elif score >= 50:

        quality = "FAIR"

    elif score >= 25:

        quality = "POOR"

    else:

        quality = "CRITICAL"

    return {
        "score": score,
        "quality": quality,
        "description": (
            f"Network quality is {quality.lower()}."
        ),
    }


# ============================================================
# INTELLIGENCE RECOMMENDATION
# ============================================================

def generate_intelligence(
    score: int,
    latency: Optional[float],
    jitter: Optional[float],
    packet_loss: Optional[float],
) -> dict[str, str]:

    if score >= 90:

        return {
            "priority": "LOW",
            "action": "Maintain connection",
            "message": (
                "Current network conditions are strong."
            ),
        }

    if score >= 75:

        return {
            "priority": "NORMAL",
            "action": "Continue monitoring",
            "message": (
                "The connection is stable."
            ),
        }

    if score >= 50:

        return {
            "priority": "MEDIUM",
            "action": "Monitor performance",
            "message": (
                "Network quality is moderate."
            ),
        }

    if score >= 25:

        return {
            "priority": "HIGH",
            "action": "Consider network switch",
            "message": (
                "A better available connection "
                "may improve performance."
            ),
        }

    return {
        "priority": "CRITICAL",
        "action": "Check connectivity",
        "message": (
            "Network conditions require immediate attention."
        ),
    }


# ============================================================
# NETWORK SNAPSHOT
# ============================================================

def collect_network_snapshot() -> dict[str, Any]:

    started = time.perf_counter()

    hostname = get_hostname()

    local_ip = get_local_ip()

    gateway = get_default_gateway()

    interface = get_network_interface()

    connection_type = detect_connection_type()

    wifi = get_wifi_info()

    internet = check_internet()

    latency = None
    jitter = None

    if internet:

        latency = measure_latency()

        jitter = measure_jitter()

    packet_loss = None

    score_data = calculate_network_score(
        latency=latency,
        jitter=jitter,
        packet_loss=packet_loss,
        internet=internet,
    )

    intelligence = generate_intelligence(
        score=score_data["score"],
        latency=latency,
        jitter=jitter,
        packet_loss=packet_loss,
    )

    elapsed = (
        time.perf_counter()
        - started
    ) * 1000

    snapshot = {
        "timestamp": utc_now(),

        "hostname": hostname,

        "local_ip": local_ip,

        "gateway": gateway,

        "interface": interface,

        "connection_type": connection_type,

        "internet": internet,

        "wifi": wifi,

        "latency_ms": latency,

        "jitter_ms": jitter,

        "packet_loss_percent": packet_loss,

        "signal": wifi.get("signal"),

        "download_mbps": None,

        "upload_mbps": None,

        "score": score_data["score"],

        "quality": score_data["quality"],

        "score_description":
            score_data["description"],

        "intelligence": intelligence,

        "collection_time_ms":
            round(elapsed, 2),
    }

    return snapshot


# ============================================================
# DATABASE INITIALIZATION
# ============================================================

def initialize_database() -> None:

    if not DATABASE_AVAILABLE:

        print(
            "WARNING: database.py could not be imported."
        )

        print(
            DATABASE_IMPORT_ERROR
        )

        return

    try:

        result = initialize_intellilink()

        print(
            "IntelliLink database initialized."
        )

        if isinstance(result, dict):

            print(
                "Device:",
                result.get(
                    "device",
                    result.get(
                        "device_id",
                        "N/A",
                    ),
                ),
            )

    except Exception as error:

        print(
            "Database initialization error:",
            error,
        )


# ============================================================
# STARTUP
# ============================================================

@app.on_event("startup")
async def startup_event():

    initialize_database()

    try:

        if DATABASE_AVAILABLE:

            log_event(
                event_type="APPLICATION_START",
                severity="INFO",
                message=(
                    f"{APP_NAME} "
                    f"version {APP_VERSION} started."
                ),
            )

    except Exception as error:

        print(
            "Startup event logging failed:",
            error,
        )


# ============================================================
# SHUTDOWN
# ============================================================

@app.on_event("shutdown")
async def shutdown_event():

    try:

        if DATABASE_AVAILABLE:

            log_event(
                event_type="APPLICATION_STOP",
                severity="INFO",
                message=(
                    f"{APP_NAME} stopped."
                ),
            )

    except Exception:

        pass


# ============================================================
# ROOT
# ============================================================

@app.get(
    "/",
    response_class=HTMLResponse,
)
async def root():

    if INDEX_FILE.exists():

        return INDEX_FILE.read_text(
            encoding="utf-8"
        )

    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{APP_NAME}</title>
    </head>
    <body>
        <h1>{APP_NAME}</h1>
        <p>Frontend file not found.</p>
        <p>API: /api/{API_VERSION}</p>
    </body>
    </html>
    """


# ============================================================
# HEALTH
# ============================================================

@app.get("/health")
async def health():

    database_status = "unavailable"

    if DATABASE_AVAILABLE:

        try:

            db_health = database_health()

            database_status = (
                db_health.get(
                    "status",
                    "unknown",
                )
                if isinstance(
                    db_health,
                    dict,
                )
                else "available"
            )

        except Exception:

            database_status = "error"

    return {
        "status": "healthy",

        "application": APP_NAME,

        "version": APP_VERSION,

        "api_version": API_VERSION,

        "database": database_status,

        "database_available":
            DATABASE_AVAILABLE,

        "uptime_seconds":
            round(
                time.time()
                - START_TIME,
                2,
            ),

        "timestamp": utc_now(),
    }


# ============================================================
# API INFORMATION
# ============================================================

@app.get(
    f"/api/{API_VERSION}"
)
async def api_information():

    return {
        "application": APP_NAME,

        "version": APP_VERSION,

        "api_version": API_VERSION,

        "product_family": PRODUCT_FAMILY,

        "manufacturer": MANUFACTURER,

        "developer": DEVELOPER,

        "device_type": DEVICE_TYPE,

        "database":
            str(DATABASE_PATH)
            if DATABASE_PATH
            else None,

        "database_available":
            DATABASE_AVAILABLE,

        "endpoints": [
            "/health",
            f"/api/{API_VERSION}/device",
            f"/api/{API_VERSION}/network",
            f"/api/{API_VERSION}/wifi",
            f"/api/{API_VERSION}/network/latency",
            f"/api/{API_VERSION}/network/snapshot",
            f"/api/{API_VERSION}/network/score",
            f"/api/{API_VERSION}/diagnostics",
            f"/api/{API_VERSION}/status",
            f"/api/{API_VERSION}/speed-test",
        ],
    }


# ============================================================
# DEVICE
# ============================================================

@app.get(
    f"/api/{API_VERSION}/device"
)
async def device_information():

    if not DATABASE_AVAILABLE:

        raise HTTPException(
            status_code=503,
            detail=(
                "Database service is unavailable."
            ),
        )

    try:

        device = get_device()

        if not device:

            device = create_device()

        platform_info = get_platform_info()

        local_ip = get_local_ip()

        hostname = get_hostname()

        update_data = {
            "local_ip": local_ip,
            "hostname": hostname,
        }

        try:

            update_device(
                update_data
            )

        except Exception:

            pass

        device = get_device()

        device = device or {}

        return {
            **device,

            "platform_system":
                platform_info["system"],

            "platform_release":
                platform_info["release"],

            "platform_architecture":
                platform_info["architecture"],

            "platform_python":
                platform_info["python_version"],

            "runtime_hostname":
                hostname,

            "runtime_local_ip":
                local_ip,

            "timestamp": utc_now(),
        }

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=str(error),
        )


# ============================================================
# DEVICE SETTINGS
# ============================================================

@app.get(
    f"/api/{API_VERSION}/device/settings"
)
async def device_settings():

    if not DATABASE_AVAILABLE:

        raise HTTPException(
            status_code=503,
            detail="Database unavailable.",
        )

    try:

        return get_device_settings()

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=str(error),
        )


# ============================================================
# NETWORK
# ============================================================

@app.get(
    f"/api/{API_VERSION}/network"
)
async def network_information():

    interface = get_network_interface()

    local_ip = get_local_ip()

    gateway = get_default_gateway()

    connection_type = detect_connection_type()

    wifi = get_wifi_info()

    internet = check_internet()

    return {
        "type": connection_type,

        "connection_type":
            connection_type,

        "name":
            wifi.get("ssid"),

        "ssid":
            wifi.get("ssid"),

        "local_ip":
            local_ip,

        "ip":
            local_ip,

        "gateway":
            gateway,

        "interface":
            interface,

        "internet":
            internet,

        "status":
            "CONNECTED"
            if internet
            else "OFFLINE",

        "timestamp":
            utc_now(),
    }


# ============================================================
# WIFI
# ============================================================

@app.get(
    f"/api/{API_VERSION}/wifi"
)
async def wifi_information():

    return get_wifi_info()


# ============================================================
# LATENCY
# ============================================================

@app.get(
    f"/api/{API_VERSION}/network/latency"
)
async def network_latency():

    internet = check_internet()

    if not internet:

        return {
            "available": False,

            "latency_ms": None,

            "jitter_ms": None,

            "message":
                "Internet connection unavailable.",
        }

    latency = measure_latency()

    jitter = measure_jitter()

    return {
        "available": True,

        "latency_ms": latency,

        "jitter_ms": jitter,

        "target": "1.1.1.1:443",

        "timestamp": utc_now(),
    }


# ============================================================
# NETWORK SNAPSHOT
# ============================================================

@app.get(
    f"/api/{API_VERSION}/network/snapshot"
)
async def network_snapshot():

    global LAST_NETWORK_SNAPSHOT

    snapshot = collect_network_snapshot()

    LAST_NETWORK_SNAPSHOT = snapshot

    # --------------------------------------------------------
    # Save snapshot to database
    # --------------------------------------------------------

    if DATABASE_AVAILABLE:

        try:

            save_network_sample(
                snapshot
            )

        except Exception as error:

            print(
                "Could not save network sample:",
                error,
            )

    return snapshot


# ============================================================
# NETWORK SCORE
# ============================================================

@app.get(
    f"/api/{API_VERSION}/network/score"
)
async def network_score():

    if LAST_NETWORK_SNAPSHOT:

        snapshot = LAST_NETWORK_SNAPSHOT

    else:

        snapshot = collect_network_snapshot()

    score = snapshot.get(
        "score"
    )

    quality = snapshot.get(
        "quality"
    )

    intelligence = snapshot.get(
        "intelligence"
    )

    return {
        "score": score,

        "quality": quality,

        "description":
            snapshot.get(
                "score_description"
            ),

        "intelligence":
            intelligence,

        "latency_ms":
            snapshot.get(
                "latency_ms"
            ),

        "jitter_ms":
            snapshot.get(
                "jitter_ms"
            ),

        "packet_loss_percent":
            snapshot.get(
                "packet_loss_percent"
            ),

        "timestamp":
            snapshot.get(
                "timestamp",
                utc_now(),
            ),
    }


# ============================================================
# DIAGNOSTICS
# ============================================================

@app.get(
    f"/api/{API_VERSION}/diagnostics"
)
async def diagnostics():

    global LAST_DIAGNOSTICS

    platform_info = get_platform_info()

    interface = get_network_interface()

    gateway = get_default_gateway()

    internet = check_internet()

    python_version = (
        platform_info[
            "python_version"
        ]
    )

    if internet:

        status = "PASS"

    else:

        status = "WARNING"

    diagnostics_data = {
        "status": status,

        "python": python_version,

        "python_version":
            python_version,

        "interface":
            interface,

        "network_interface":
            interface,

        "gateway":
            gateway,

        "default_gateway":
            gateway,

        "internet":
            "PASS"
            if internet
            else "FAIL",

        "internet_status":
            internet,

        "platform":
            platform_info,

        "message":
            (
                "Diagnostics completed successfully."
                if internet
                else
                "Diagnostics completed, but internet "
                "connectivity is unavailable."
            ),

        "timestamp": utc_now(),
    }

    LAST_DIAGNOSTICS = diagnostics_data

    if DATABASE_AVAILABLE:

        try:

            save_diagnostic(
                diagnostics_data
            )

        except Exception as error:

            print(
                "Could not save diagnostic:",
                error,
            )

    return diagnostics_data


# ============================================================
# STATUS
# ============================================================

@app.get(
    f"/api/{API_VERSION}/status"
)
async def application_status():

    device = None

    if DATABASE_AVAILABLE:

        try:

            device = get_device()

        except Exception:

            device = None

    network = (
        LAST_NETWORK_SNAPSHOT
        or collect_network_snapshot()
    )

    return {
        "application": APP_NAME,

        "version": APP_VERSION,

        "status": "RUNNING",

        "uptime_seconds":
            round(
                time.time()
                - START_TIME,
                2,
            ),

        "database_available":
            DATABASE_AVAILABLE,

        "device_id":
            device.get(
                "device_id"
            )
            if device
            else None,

        "network_score":
            network.get(
                "score"
            ),

        "network_quality":
            network.get(
                "quality"
            ),

        "internet":
            network.get(
                "internet"
            ),

        "timestamp": utc_now(),
    }


# ============================================================
# SPEED TEST
# ============================================================

@app.get(
    f"/api/{API_VERSION}/speed-test"
)
async def speed_test():

    global LAST_SPEED_TEST

    started = time.perf_counter()

    target_host = "1.1.1.1"

    target_port = 443

    latency = measure_latency(
        target_host,
        target_port,
        attempts=3,
    )

    internet = (
        latency is not None
    )

    elapsed = (
        time.perf_counter()
        - started
    ) * 1000

    result = {
        "status":
            "COMPLETED"
            if internet
            else "FAILED",

        "server":
            f"{target_host}:{target_port}",

        "latency_ms":
            latency,

        # ----------------------------------------------------
        # Deliberately NOT fabricated.
        # Full throughput measurement requires a proper
        # download/upload test implementation.
        # ----------------------------------------------------

        "download_mbps":
            None,

        "upload_mbps":
            None,

        "download_speed":
            None,

        "upload_speed":
            None,

        "internet":
            internet,

        "test_duration_ms":
            round(
                elapsed,
                2,
            ),

        "message":
            (
                "Connection benchmark completed. "
                "Full download/upload throughput "
                "measurement is not enabled yet."
                if internet
                else
                "Connection benchmark failed."
            ),

        "timestamp":
            utc_now(),
    }

    LAST_SPEED_TEST = result

    if DATABASE_AVAILABLE:

        try:

            save_speed_test(
                result
            )

        except Exception as error:

            print(
                "Could not save speed test:",
                error,
            )

    return result


# ============================================================
# DASHBOARD SUMMARY
# ============================================================

@app.get(
    f"/api/{API_VERSION}/dashboard"
)
async def dashboard():

    if DATABASE_AVAILABLE:

        try:

            return get_dashboard_summary()

        except Exception as error:

            print(
                "Dashboard summary error:",
                error,
            )

    network = (
        LAST_NETWORK_SNAPSHOT
        or collect_network_snapshot()
    )

    return {
        "application": APP_NAME,

        "version": APP_VERSION,

        "network": network,

        "timestamp": utc_now(),
    }


# ============================================================
# NETWORK HISTORY
# ============================================================

@app.get(
    f"/api/{API_VERSION}/network/history"
)
async def network_history(
    limit: int = 50,
):

    if not DATABASE_AVAILABLE:

        raise HTTPException(
            status_code=503,
            detail="Database unavailable.",
        )

    limit = max(
        1,
        min(
            limit,
            500,
        ),
    )

    try:

        return {
            "items":
                get_network_history(
                    limit=limit
                ),
            "limit": limit,
        }

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=str(error),
        )


# ============================================================
# SPEED HISTORY
# ============================================================

@app.get(
    f"/api/{API_VERSION}/speed/history"
)
async def speed_history(
    limit: int = 50,
):

    if not DATABASE_AVAILABLE:

        raise HTTPException(
            status_code=503,
            detail="Database unavailable.",
        )

    limit = max(
        1,
        min(
            limit,
            500,
        ),
    )

    try:

        return {
            "items":
                get_speed_history(
                    limit=limit
                ),
            "limit": limit,
        }

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=str(error),
        )


# ============================================================
# DIAGNOSTIC HISTORY
# ============================================================

@app.get(
    f"/api/{API_VERSION}/diagnostics/history"
)
async def diagnostics_history(
    limit: int = 50,
):

    if not DATABASE_AVAILABLE:

        raise HTTPException(
            status_code=503,
            detail="Database unavailable.",
        )

    limit = max(
        1,
        min(
            limit,
            500,
        ),
    )

    try:

        return {
            "items":
                get_diagnostics(
                    limit=limit
                ),
            "limit": limit,
        }

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=str(error),
        )


# ============================================================
# EVENT HISTORY
# ============================================================

@app.get(
    f"/api/{API_VERSION}/events"
)
async def event_history(
    limit: int = 100,
):

    if not DATABASE_AVAILABLE:

        raise HTTPException(
            status_code=503,
            detail="Database unavailable.",
        )

    limit = max(
        1,
        min(
            limit,
            500,
        ),
    )

    try:

        return {
            "items":
                get_events(
                    limit=limit
                ),
            "limit": limit,
        }

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=str(error),
        )


# ============================================================
# DATABASE HEALTH
# ============================================================

@app.get(
    f"/api/{API_VERSION}/database/health"
)
async def database_health_endpoint():

    if not DATABASE_AVAILABLE:

        return {
            "status": "UNAVAILABLE",

            "available": False,

            "error":
                DATABASE_IMPORT_ERROR,
        }

    try:

        result = database_health()

        return {
            "available": True,

            **(
                result
                if isinstance(
                    result,
                    dict,
                )
                else {
                    "status":
                        str(result)
                }
            ),
        }

    except Exception as error:

        return {
            "available": False,

            "status": "ERROR",

            "error": str(error),
        }


# ============================================================
# GLOBAL EXCEPTION HANDLER
# ============================================================

@app.exception_handler(Exception)
async def global_exception_handler(
    request,
    exc,
):

    print(
        "Unhandled application error:",
        exc,
    )

    return JSONResponse(
        status_code=500,

        content={
            "error": "Internal Server Error",

            "message":
                "An unexpected application error occurred.",

            "path":
                str(request.url.path),

            "timestamp":
                utc_now(),
        },
    )


# ============================================================
# LOCAL DEVELOPMENT SERVER
# ============================================================

if __name__ == "__main__":

    import uvicorn

    port = int(
        os.getenv(
            "PORT",
            "8000",
        )
    )

    uvicorn.run(
        "main:app",

        host="0.0.0.0",

        port=port,

        reload=False,
    )
